BUNDLE_NAME = Alarm
Alarm_FILES = Alarm.m ListValue.m Add.m Overview.m Cell.m
Alarm_INSTALL_PATH = /Library/ProWidgets/Widgets/
Alarm_FRAMEWORKS = UIKit CoreGraphics QuartzCore
Alarm_PRIVATE_FRAMEWORKS = MobileTimer
Alarm_LIBRARIES = prowidgets
Alarm_CFLAGS = -I../../
Alarm_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk