TWEAK_NAME = PWDictionarySubstrate
PWDictionarySubstrate_FILES = PWDictionarySubstrate.xm
PWDictionarySubstrate_FRAMEWORKS = CoreFoundation Foundation UIKit
PWDictionarySubstrate_CFLAGS = -I../../../
PWDictionarySubstrate_LDFLAGS = -L../../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk