BUNDLE_NAME = TestTheme
TestTheme_FILES = TestTheme.m
TestTheme_INSTALL_PATH = /Library/ProWidgets/Themes/
TestTheme_FRAMEWORKS = UIKit CoreGraphics QuartzCore
TestTheme_LIBRARIES = prowidgets
TestTheme_CFLAGS = -I../../
TestTheme_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk