TWEAK_NAME = PWAPIMessage
PWAPIMessage_FILES = PWAPIMessage.m
PWAPIMessage_FRAMEWORKS = CoreFoundation Foundation UIKit
PWAPIMessage_LIBRARIES = objcipc
PWAPIMessage_CFLAGS = -I../../

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk