TWEAK_NAME = PWAPIMessage
PWAPIMessage_FILES = PWAPIMessage.x
PWAPIMessage_FRAMEWORKS = CoreFoundation Foundation UIKit MessageUI
PWAPIMessage_PRIVATE_FRAMEWORKS = ChatKit
PWAPIMessage_LIBRARIES = objcipc
PWAPIMessage_CFLAGS = -I../../

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk