BUNDLE_NAME = Spotify
Spotify_FILES = Spotify.m ViewController.m Theme.m
Spotify_INSTALL_PATH = /Library/ProWidgets/Widgets/
Spotify_FRAMEWORKS = UIKit CoreGraphics QuartzCore
Spotify_LIBRARIES = prowidgets objcipc
Spotify_CFLAGS = -I../../
Spotify_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)
Spotify_BUNDLE_EXTENSION = widget

#SUBPROJECTS = SpotifySubstrate

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
include $(THEOS_MAKE_PATH)/aggregate.mk