TWEAK_NAME = AuthenticatorSubstrate
AuthenticatorSubstrate_FILES = AuthenticatorSubstrate.m
AuthenticatorSubstrate_FRAMEWORKS = CoreFoundation Foundation UIKit
AuthenticatorSubstrate_LIBRARIES = objcipc
AuthenticatorSubstrate_CFLAGS = -I../../../

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk