BUNDLE_NAME = Notes
Notes_FILES = Notes.m Add.m List.m Content.m Cell.m
Notes_INSTALL_PATH = /Library/ProWidgets/Widgets/
Notes_FRAMEWORKS = UIKit CoreGraphics QuartzCore
Notes_PRIVATE_FRAMEWORKS = Notes
Notes_LIBRARIES = prowidgets
Notes_CFLAGS = -I../../
Notes_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)
Notes_BUNDLE_EXTENSION = widget

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk