BUNDLE_NAME = DarkBlur
DarkBlur_FILES = DarkBlur.m
DarkBlur_INSTALL_PATH = /Library/ProWidgets/Themes/
DarkBlur_FRAMEWORKS = UIKit CoreGraphics QuartzCore
DarkBlur_LIBRARIES = prowidgets
DarkBlur_CFLAGS = -I../../
DarkBlur_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk