BUNDLE_NAME = Test
Test_FILES = 
#Test.m
Test_INSTALL_PATH = /Library/ProWidgets/Widgets/
Test_FRAMEWORKS = UIKit CoreGraphics QuartzCore
Test_LIBRARIES = prowidgets
Test_CFLAGS = -I../../
Test_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)
Test_BUNDLE_EXTENSION = widget

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk