TWEAK_NAME = PWBrowserSubstrate
PWBrowserSubstrate_FILES = PWBrowserSubstrate.xm
PWBrowserSubstrate_FRAMEWORKS = CoreFoundation Foundation UIKit
PWBrowserSubstrate_PRIVATE_FRAMEWORKS = MobileTimer
PWBrowserSubstrate_CFLAGS = -I../../../
PWBrowserSubstrate_LDFLAGS = -L../../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk