TWEAK_NAME = PWCalendarSubstrate
PWCalendarSubstrate_FILES = PWCalendarSubstrate.xm
PWCalendarSubstrate_FRAMEWORKS = CoreFoundation Foundation UIKit
PWCalendarSubstrate_PRIVATE_FRAMEWORKS = DataDetectorsCore DataDetectorsUI
PWCalendarSubstrate_CFLAGS = -I../../../
PWCalendarSubstrate_LDFLAGS = -L../../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk