BUNDLE_NAME = Mail
Mail_FILES = Mail.m
Mail_INSTALL_PATH = /Library/ProWidgets/Widgets/
Mail_FRAMEWORKS = UIKit CoreGraphics QuartzCore
Mail_PRIVATE_FRAMEWORKS = Notes
Mail_LIBRARIES = prowidgets
Mail_CFLAGS = -I../../
Mail_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk