TWEAK_NAME = PWAPIMail
PWAPIMail_FILES = PWAPIMail.m
PWAPIMail_FRAMEWORKS = CoreFoundation Foundation UIKit
PWAPIMail_LIBRARIES = objcipc
PWAPIMail_CFLAGS = -I../../

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk