BUNDLE_NAME = Calendar
Calendar_FILES = Calendar.m ListValue.m Add.m Overview.m Cell.m
Calendar_INSTALL_PATH = /Library/ProWidgets/Widgets/
Calendar_FRAMEWORKS = UIKit CoreGraphics QuartzCore EventKit
Calendar_PRIVATE_FRAMEWORKS = 
Calendar_LIBRARIES = prowidgets
Calendar_CFLAGS = -I../../
Calendar_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk