BUNDLE_NAME = Timer
Timer_FILES = Timer.m DatePicker.m
Timer_INSTALL_PATH = /Library/ProWidgets/Widgets/
Timer_FRAMEWORKS = UIKit CoreGraphics QuartzCore
Timer_LIBRARIES = prowidgets objcipc
Timer_CFLAGS = -I../../
Timer_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)
Timer_BUNDLE_EXTENSION = widget

SUBPROJECTS = Substrate

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
include $(THEOS_MAKE_PATH)/aggregate.mk