TWEAK_NAME = PWAPIAlarm
PWAPIAlarm_FILES = PWAPIAlarm.xm
PWAPIAlarm_FRAMEWORKS = CoreFoundation Foundation UIKit
PWAPIAlarm_PRIVATE_FRAMEWORKS = MobileTimer
PWAPIAlarm_LIBRARIES = objcipc
PWAPIAlarm_CFLAGS = -I../../

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk