TWEAK_NAME = PWTimerSubstrate
PWTimerSubstrate_FILES = PWTimerSubstrate.xm
PWTimerSubstrate_FRAMEWORKS = CoreFoundation Foundation UIKit
PWTimerSubstrate_PRIVATE_FRAMEWORKS = MobileTimer
PWTimerSubstrate_LIBRARIES = objcipc
PWTimerSubstrate_CFLAGS = -I../../../

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk