ARCHS = armv7 arm64

include theos/makefiles/common.mk

BUNDLE_NAME = PWWidgetDictionary
PWWidgetDictionary_FILES = PWWidgetDictionary.mm
PWWidgetDictionary_INSTALL_PATH = /Library/PreferenceBundles
PWWidgetDictionary_FRAMEWORKS = UIKit
PWWidgetDictionary_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk