BUNDLE_NAME = Messages
Messages_FILES = Messages.m
Messages_INSTALL_PATH = /Library/ProWidgets/Widgets/
Messages_FRAMEWORKS = UIKit CoreGraphics QuartzCore
Messages_PRIVATE_FRAMEWORKS = Notes
Messages_LIBRARIES = prowidgets
Messages_CFLAGS = -I../../
Messages_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk