BUNDLE_NAME = PlainBlur
PlainBlur_FILES = PlainBlur.m
PlainBlur_INSTALL_PATH = /Library/ProWidgets/Themes/
PlainBlur_FRAMEWORKS = UIKit CoreGraphics QuartzCore
PlainBlur_LIBRARIES = prowidgets
PlainBlur_CFLAGS = -I../../
PlainBlur_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk