TWEAK_NAME = ProWidgetsListener
ProWidgetsListener_FILES = ProWidgetsListener.m
ProWidgetsListener_FRAMEWORKS = CoreFoundation Foundation UIKit
ProWidgetsListener_LIBRARIES = prowidgets activator
ProWidgetsListener_CFLAGS = -I../../
ProWidgetsListener_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk