BUNDLE_NAME = Custom
Custom_FILES = Custom.m
Custom_INSTALL_PATH = /Library/ProWidgets/Widgets/
Custom_FRAMEWORKS = UIKit CoreGraphics QuartzCore
Custom_LIBRARIES = prowidgets
Custom_CFLAGS = -I../../
Custom_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk