BUNDLE_NAME = ProWidgets
ProWidgets_FILES = ProWidgetsSection.m ProWidgetsSectionView.m PWButtonLayoutView.x
ProWidgets_INSTALL_PATH = /Library/CCLoader/Bundles
ProWidgets_FRAMEWORKS = Foundation UIKit
ProWidgets_PRIVATE_FRAMEWORKS = SpringBoardUI
ProWidgets_LIBRARIES = substrate prowidgets
ProWidgets_CFLAGS = -I../../
ProWidgets_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk